# Generated by Django 4.2.11 on 2024-03-30 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_img', models.ImageField(upload_to='cv_images/')),
                ('age', models.IntegerField()),
                ('phone_nom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('project_url', models.URLField()),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('img', models.ImageField(upload_to='portfolio_images/')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='portfolio.cv_model')),
            ],
        ),
    ]
