# Generated by Django 4.2.11 on 2024-04-03 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv_model',
            name='phone_nom',
        ),
        migrations.RemoveField(
            model_name='portfolio_model',
            name='cv',
        ),
    ]
