# Generated by Django 4.2.11 on 2024-04-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_cv_model_phone_nom_remove_portfolio_model_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio_model',
            name='parts',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
